//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenScrape.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       131
#define IDD_SELECTTABLE                 132
#define IDD_TABLEMAP                    133
#define IDD_EDITDLG                     134
#define IDD_EDIT_SIZES                  135
#define IDD_EDIT_SYMBOLS                136
#define IDB_PICKERBITMAP                137
#define IDD_EDIT_REGION                 138
#define IDB_DRAWRECTBITMAP              139
#define IDD_EDIT_FONT                   140
#define IDC_PICKERCURSOR                141
#define IDD_EDIT_HASHPOINTS             142
#define IDC_DRAWRECTCURSOR              143
#define IDD_EDIT_GR_HASHPOINTS          145
#define IDD_COPY_REGION                 146
#define IDB_BITMAP1                     152
#define IDB_NUDGEWIDERBITMAP            152
#define IDC_TABLEMAP_TREE               1000
#define IDC_LEFT                        1001
#define IDC_CURRENTREGION               1002
#define IDC_LEFT_SPIN                   1003
#define IDC_TOP                         1004
#define IDC_TOP_SPIN                    1005
#define IDC_BOTTOM                      1006
#define IDC_BOTTOM_SPIN                 1007
#define IDC_RIGHT                       1008
#define IDC_RIGHT_SPIN                  1009
#define IDC_TRANSFORM                   1010
#define IDC_ZOOM                        1011
#define IDC_RADIUS                      1012
#define IDC_RESULT                      1013
#define IDC_NEW                         1014
#define IDC_DELETE                      1015
#define IDC_EDIT                        1016
#define IDC_SORT                        1017
#define IDC_OCR_VIEW                    1017
#define IDC_CREATE_HASH                 1018
#define IDC_CREATE_IMAGE                1019
#define IDC_LIST_SELECT_TABLE           1020
#define IDC_CREATE_HASH0                1020
#define IDC_CREATE_FONT                 1021
#define IDC_EDITENTRY                   1022
#define IDC_CREATE_HASH1                1022
#define IDC_RADIUS_SPIN                 1023
#define IDC_PIXELSEPARATION             1024
#define IDC_FONTPLUS                    1025
#define IDC_HEIGHT                      1026
#define IDC_CREATE_HASH2                1026
#define IDC_FONTMINUS                   1027
#define IDC_NAME                        1028
#define IDC_CREATE_HASH3                1028
#define IDC_WIDTH                       1029
#define IDC_CROP_SPIN                   1029
#define IDC_TYPE                        1030
#define IDC_THRESHOLD_SPIN              1030
#define IDC_VALUE                       1031
#define IDC_CHARACTER                   1032
#define IDC_X                           1033
#define IDC_Y                           1034
#define IDC_BLUE                        1035
#define IDC_TITLETEXT                   1036
#define IDC_PIXELSEP                    1037
#define IDC_GREEN                       1038
#define IDC_RED                         1039
#define IDC_ALPHA                       1040
#define IDC_PICKER                      1041
#define IDC_PARSERESULTS                1042
#define IDC_ALPHA2                      1237
#define IDC_RED2                        1238
#define IDC_GREEN2                      1239
#define IDC_BLUE2                       1240
#define IDC_PICKER2                     1241
#define IDC_COLOR2_ENABLE               1242
#define IDC_ALPHA3                      1243
#define IDC_RED3                        1244
#define IDC_GREEN3                      1245
#define IDC_BLUE3                       1246
#define IDC_PICKER3                     1247
#define IDC_COLOR3_ENABLE               1248
#define IDC_LEFT2                       1249
#define IDC_TOP2                        1250
#define IDC_RIGHT2                      1251
#define IDC_BOTTOM2                     1252
#define IDC_RECT2_ENABLE                1253
#define IDC_DRAWRECT2                   1254
#define IDC_DRAWRECT                    1043
#define IDC_PARSEBUTTON                 1044
#define IDC_NUDGE_UP                    1045
#define IDC_RED_AVG                     1046
#define IDC_CHARLIST                    1047
#define IDC_GREEN_AVG                   1048
#define IDC_HASH_TYPE                   1049
#define IDC_BLUE_AVG                    1050
#define IDC_SAMPLE_IMAGE                1051
#define IDC_POINT_LIST                  1052
#define IDC_SAMPLE_BITMAP               1053
#define IDC_NUDGE_DOWN                  1054
#define IDC_ZOOM_LEVEL                  1055
#define IDC_NUDGE_LEFT                  1056
#define IDC_MOUSEPOS                    1057
#define IDC_NUDGE_RIGHT                 1058
#define IDC_NUDGE_UPLEFT                1059
#define IDC_NUDGE_UPRIGHT               1060
#define IDC_NUDGE_DOWNRIGHT             1061
#define IDC_NUDGE_DOWNLEFT              1062
#define IDC_NUDGE_TALLER                1063
#define IDC_NUDGE_SHORTER               1064
#define IDC_NUDGE_WIDER                 1065
#define IDC_NUDGE_NARROWER              1066
#define IDC_NUDGE_BIGGER                1067
#define IDC_NUDGE_SMALLER               1068
#define IDC_TEST                        1069
#define IDC_TITLETEXT_PREPROCESSED      1070
#define IDC_TRACKER_FONT_SET            1077
#define IDC_TRACKER_CARD_NUM            1078
#define IDC_TRACKER_FONT_NUM            1079
#define IDC_                            1085
#define IDC_MISSING_CARDS               1089
#define IDC_REGIONLIST                  1090
#define IDC_SOURCE                      1091
#define IDC_MISSING_FONTS               1092
#define IDC_COMBO1                      1092
#define IDC_EDIT1                       1093
#define IDC_EDITXY                      1093
#define IDC_OCRCHECK_DEFAULT            1094
#define IDC_USE_DEFAULT                 1094
#define IDC_OCRLIST_PDIFF               1095
#define IDC_OCREDIT_RECOTRESHOLD        1096
#define IDC_THRESHOLD                   1096
#define IDC_RADIO_INBUILT               1102
#define IDC_USE_CROP                    1106
#define IDC_MATCH_MODE                  1109
#define IDC_CROP_SIZE                   1110
#define IDC_IMG_PROC                    1111
#define IDC_CREATE_GROUP                1115
#define IDC_GROUP_BOX                   1116
#define IDC_GROUP_COLOR                 1117
#define IDC_DELETE_PLAYER               1118
#define IDC_DELETE_PLAYER_REGIONS       1119
#define IDC_DUPLICATE_PLAYER            1120
#define IDC_DUPLICATE_GROUP_TO_PLAYER   1121
#define IDC_UPDATE_OCR_NOW              1134
#define IDC_IMAGE_PROC_PRESET           1135
#define IDC_IMAGE_PROC_PRESET_ADD       1136
#define IDC_IMAGE_PROC_PRESET_DELETE    1137
#define IDC_IMAGE_PROC_PRESET_LOAD      1138
#define IDC_SHARPEN                     1139
#define IDC_SHARPEN_SPIN                1140
#define ID_MAIN_TOOLBAR_GREENCIRCLE     32771
#define ID_VIEW_CONNECTTOWINDOW         32772
#define ID_VIEW_SHOWREGIONBOXES         32774
#define ID_EDIT_UPDATEHASHES            32775
#define ID_MAIN_TOOLBAR_REFRESH         32776
#define ID_VIEW_REFRESH                 32777
#define ID_VIEW_CURRENTWINDOWSIZE       32778
#define ID_EDIT_DUPLICATEREGION         32779
#define ID_EDIT_COPYREGION              32780
#define ID_VIEW_GROUPREGIONS            32781
#define ID_GROUPREGIONS_BYTYPE          32782
#define ID_GROUPREGIONS_BYNAME          32783
#define ID_MAIN_TOOLBAR_PREV            32785
#define ID_MAIN_TOOLBAR_NEXT            32786
#define ID_MAIN_TOOLBAR_TRAINING        32796
#define ID_AUTO_CAPTURE                 32801
#define ID_AUTO_CAPTURE_BACK            32802
#define ID_AUTO_CAPTURE_NEXT            32803
#define ID_AUTO_CAPTURE_CLEAR           32804
#define ID_AUTO_CAPTURE_REFRESH         32805
#define ID_VIEW_PREV                    32787
#define ID_VIEW_NEXT                    32788
#define ID_TOOLS_CLONEREGIONS           32789
#define ID_EDIT_ENABLETEXTDETECTION     32790
#define ID_EDIT_TEXTDETECTIONSETTINGS   32791
#define ID_EDIT_                        32792
#define ID_VIEW_SHOW_PREVIEW            32793
#define ID_OPERATIONS_CREATE_HASHES_IMAGES_0 32794
#define ID_TOOLS_SHIFTREGIONS           32795
#define ID_DB_IMPORT_FILE               32797
#define ID_DB_IMPORT_FOLDER             32798
#define ID_DB_DELETE_TABLEMAP           32806
#define IDD_SAVECHANGES_DB              154
#define IDC_SC_MESSAGE                  1267
#define IDC_SC_SAVE                     1268
#define IDC_SC_SAVEAS                   1269
#define IDC_SC_DISCARD                  1270
#define ID_TOOLS_SETTINGS               32799
#define IDD_SETTINGS                    153
#define IDC_SETTINGS_GROUPS             1200
#define IDC_EDIT_A0_MODEL               1201
#define IDC_EDIT_A1_MODEL               1202
#define IDC_LST_DECIMAL_FIELDS          1203
#define IDC_SET_GENERAL_TEXT            1204
#define IDC_SET_FIELDS_A0LBL            1205
#define IDC_SET_FIELDS_A1LBL            1206
#define IDC_SET_FIELDS_DECLBL           1207
#define IDC_SET_ADVANCED_TEXT           1208
#define IDC_SET_PAGE_TITLE              1209
#define IDC_BTN_A0_BROWSE               1210
#define IDC_BTN_A1_BROWSE               1211
#define IDC_CHK_NO_PREPROCESS           1212
#define IDC_CHK_NO_WHITELIST            1213
#define IDC_SET_MODEL_LBL               1214
#define IDC_SET_THRESHOLD               1215
#define IDC_SET_THRESHOLD_SPIN          1216
#define IDC_SET_THRESHOLD_LBL           1217
#define IDC_SET_MODE                    1218
#define IDC_SET_MODE_LBL                1219
#define IDC_CHK_LIVE_POLL               1220
#define IDC_SET_LIVE_HINT               1221
#define IDC_SET_ORIG_VIEW               1222
#define IDC_SET_ORIG_LBL                1223
#define IDC_SET_OCR_VIEW                1224
#define IDC_SET_OCR_LBL                 1225
#define IDC_SET_ORIG_LEFT               1226
#define IDC_SET_ORIG_RIGHT              1227
#define IDC_SET_SPLIT_LBL               1228
#define IDC_SET_RESULT                  1229
#define IDC_SET_RESULT_LBL              1230
#define IDC_SET_RESULT_LEFT             1231
#define IDC_SET_RESULT_RIGHT            1232
#define IDC_SET_RESULT_LR_LBL           1233
#define IDC_CHK_NO_CHARSPACING          1234
#define IDC_LABEL                       65535

// Next default values for new objects
// 
#define IDC_LST_SCRAPE_FIELDS           1235
#define IDC_SET_SCRAPE_LBL              1236
#define IDC_LOCKED_LABEL                1255
#define IDC_SET_ACC_TEXT                1256
#define IDC_SET_ACC_LBL                 1257
#define IDC_SET_ACC_INTERVAL            1258
#define IDC_SET_PW_TEXT                 1259
#define IDC_SET_PW_CPUS_LBL             1260
#define IDC_SET_PW_CPUS                 1261
#define IDC_SET_PW_WPC_LBL              1262
#define IDC_SET_PW_WPC                  1263
#define IDC_CAPTURE_COUNT               1264
#define IDC_SET_PW_HISS_OCR             1265
#define IDC_CAPTURE_INDEX               1266
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1271
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
