//******************************************************************************
//
// This file is part of the OpenHoldem project
//    Source code:           https://github.com/OpenHoldem/openholdembot/
//    Forums:                http://www.maxinmontreal.com/forums/index.php
//    Licensed under GPL v3: http://www.gnu.org/licenses/gpl.html
//
//******************************************************************************
//
// Purpose:
//
//******************************************************************************

#include "stdafx.h"
#include "CParseErrors.h"

#include <process.h>   // _beginthreadex -- the non-blocking parse-error window runs on its own thread
#include "CFormulaParser.h"
#include "CTokenizer.h"
#include "..\DLLs\WindowFunctions_DLL\window_functions.h"
#include "..\DLLs\StringFunctions_DLL\string_functions.h"
#include "TokenizerConstants.h"

bool CParseErrors::_is_error = false;
CString CParseErrors::_last_error_message = "";
CString CParseErrors::_all_errors = "";       // ALL parse errors of this pass, accumulated into one buffer

// ---------------------------------------------------------------------------
// Non-blocking, COPYABLE parse-error window. A blocking modal per error halted the bot (and popped one
// dialog per error). Instead we ACCUMULATE every error into _all_errors and, at parse-end, show them
// ONCE here -- a read-only multiline EDIT (select-all + copy) on its OWN thread + message loop, so the
// parse / load thread is never blocked. [Emrald: non-blocking + one combined, copyable message]
// ---------------------------------------------------------------------------
static LRESULT CALLBACK ParseErrWndProc(HWND h, UINT m, WPARAM w, LPARAM l) {
  if (m == WM_SIZE) {
    HWND e = GetWindow(h, GW_CHILD);
    if (e != NULL) MoveWindow(e, 0, 0, LOWORD(l), HIWORD(l), TRUE);
    return 0;
  }
  if (m == WM_CLOSE) { DestroyWindow(h); return 0; }
  if (m == WM_DESTROY) { PostQuitMessage(0); return 0; }
  return DefWindowProc(h, m, w, l);
}

static unsigned __stdcall ParseErrorWindowThread(void *param) {
  CString *text = (CString *)param;
  HINSTANCE hInst = AfxGetInstanceHandle();
  static const TCHAR *kCls = _T("HissParseErrorWnd");
  WNDCLASSEX wc; ZeroMemory(&wc, sizeof(wc)); wc.cbSize = sizeof(wc);
  wc.lpfnWndProc = ParseErrWndProc; wc.hInstance = hInst; wc.lpszClassName = kCls;
  wc.hCursor = LoadCursor(NULL, IDC_ARROW); wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
  RegisterClassEx(&wc);   // harmless if already registered for this run
  HWND hwnd = CreateWindowEx(WS_EX_TOPMOST, kCls,
    _T("Hiss Parse Errors  -  read-only; click in the box, Ctrl+A then Ctrl+C to copy"),
    WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT, 760, 480, NULL, NULL, hInst, NULL);
  if (hwnd != NULL) {
    HWND hEdit = CreateWindowEx(0, _T("EDIT"), NULL,
      WS_CHILD | WS_VISIBLE | WS_VSCROLL | WS_HSCROLL | ES_MULTILINE | ES_READONLY | ES_AUTOVSCROLL | ES_AUTOHSCROLL,
      0, 0, 0, 0, hwnd, NULL, hInst, NULL);
    HFONT font = (HFONT)GetStockObject(ANSI_FIXED_FONT);
    if (hEdit != NULL) {
      SendMessage(hEdit, WM_SETFONT, (WPARAM)font, TRUE);
      CString t = *text; t.Replace("\n", "\r\n"); t.Replace("\r\r\n", "\r\n");
      SetWindowText(hEdit, t);
      RECT rc; GetClientRect(hwnd, &rc);
      MoveWindow(hEdit, 0, 0, rc.right, rc.bottom, TRUE);
    }
    ShowWindow(hwnd, SW_SHOW);
    UpdateWindow(hwnd);
    MSG msg;
    while (GetMessage(&msg, NULL, 0, 0) > 0) { TranslateMessage(&msg); DispatchMessage(&msg); }
  }
  delete text;
  return 0;
}

void CParseErrors::Error(CString short_message) {
  if (short_message.Right(1) != "\n") {
    short_message += "\n";
  }
  CString message;
  message.Format("%s%s%s%s%s%s%s%i%s%s%i%s%s%s%s%s%s%s%s%s",
    "Error: ", short_message,
    "==============================================\n",
    "Function: ", CTokenizer::CurrentFunctionName(), "\n",
    "Line absolute: ", CTokenizer::LineAbsolute(), "\n",
    "Line relative: ", CTokenizer::LineRelative(), "\n",
    "File: ", CTokenizer::InputFile(), "\n",
    "==============================================\n",
    "\n",
    ErroneousCodeSnippet(), "\n",
    "==============================================\n");
  // Avoid duplicate messages, which might be generated by the parser or the tokenizer (a char checked
  // multiple times). ACCUMULATE rather than popping a blocking modal per error -- FlushErrors() shows the
  // whole set once, non-blocking + copyable, at parse-end. [Emrald]
  if (_last_error_message == message) {
    return;
  }
  _last_error_message = message;
  _is_error = true;
  _all_errors += message;
  _all_errors += "\n";
}

void CParseErrors::FlushErrors() {
  // Called at parse-end: if any errors accumulated, show them ONCE in the non-blocking copyable window.
  if (_all_errors.IsEmpty()) {
    return;
  }
  CString header;
  header.Format("Hiss collected parse errors below. The strategy still loads (these lines fail soft); "
                "copy this if you want it fixed.\n\n");
  CString *text = new CString(header + _all_errors);
  _all_errors = "";   // consume; the next parse pass re-accumulates
  unsigned tid = 0;
  HANDLE h = (HANDLE)_beginthreadex(NULL, 0, ParseErrorWindowThread, text, 0, &tid);
  if (h != NULL) {
    CloseHandle(h);
  } else {
    delete text;   // thread didn't start -> no leak
  }
}

void CParseErrors::ErrorUnknownIdentifier(CString name) {
  CString message;
  message.Format("Unknown identifier: %s", name);
  Error(message);
}

void CParseErrors::UnexpectedToken(CString short_error_message, CString expected, int token_found_instead) {
  CString message;
  message = short_error_message + expected;
  message += "Found: " + TokenVerboseExplained(token_found_instead) + "\n";
  Error(message);
}

CString CParseErrors::ErroneousCodeSnippet() {
  // We have seen functions up to several 1000 lines 
  // (insane Shanky-style) and lines up 5000 characters
  // (auto-generated code).
  // Here we want to build some code-snippet 
  // that fits into a message-box. ;-)
  const int kLinesOfCodeToShow = 5;
  const int kMaxCharactersPerLineToShow = 60;
  char* remaining_input = CTokenizer::RemainingInput();
  if (remaining_input == NULL) return "";
  CString erroneous_code_snippet = "";
  for (int i = 0; i < kLinesOfCodeToShow; i++) {
    for (int j = 0; j < kMaxCharactersPerLineToShow; j++) {
      char next_character = remaining_input[j];
      erroneous_code_snippet += next_character;
      if (next_character == '\n') {
        // End of line reached
        // Therefore terminate this line early
        break;
      }
      else if (next_character == '\0') {
        // End of function reached
        // Therefore terminate completely
        goto EndOfOuterLoop;
      }
    }
    if (RightCharacter(erroneous_code_snippet) != '\n') {
      erroneous_code_snippet += '\n';
    }
    // Skip to end of line 
    char next_character;
    do {
      next_character = *remaining_input;
      remaining_input++;
    } while ((next_character != '\n') && (next_character != '\0'));
    if (next_character == '\0') {
      // End of input reached
      // Can't continue with the for-loop
      break;
    }
	}
EndOfOuterLoop:
  return erroneous_code_snippet;
}

void CParseErrors::ClearErrorStatus() {
  _is_error = false;
  _last_error_message = "";
  _all_errors = "";
}

bool CParseErrors::AnyError() {
  return _is_error;
}

void CParseErrors::MessageBox_Formula_Error(CString Message, CString Title) {
  // Make sure, that we have a line-break at the end.
  if (Message.Right(1) != "\n") {
    Message += "\n";
  }
  if (p_formula_parser->IsParsing()) {
    CParseErrors::Error(Message);
  }
  else {
    MessageBox_Error_Warning(Message, Title);
  }
}